Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
    sensor_tmp112.c
    """)

group = DefineGroup('nu_pkgs_tmp112', src, depend = ['NU_PKG_USING_TMP112'], CPPPATH = CPPPATH)

Return('group')
